apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixellib-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: pixelliblabel

  template:
    metadata:
      name: pixellibpod
      labels:
        app: pixelliblabel  

    spec:
      containers:
        - name: deploypixellib
          image: ayoolaolafenwa/pixellibapi
          ports:
            - containerPort: 5000

---
apiVersion: v1            
kind: Service
metadata:
  name: pixellib-service

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000

  selector:
    app: pixelliblabel  
